function Link({ href, children }) {
  return <a href={href} target="_blank" rel="noopener noreferrer">{children}</a>;
}

function EraSourceBlock({ year, title, authentic, sources }) {
  return (
    <div className="about__era">
      <div className="about__era-head">
        <span className="about__era-year">{year}</span>
        <span className="about__era-title">{title}</span>
      </div>
      <div className="about__era-row">
        <span className="about__era-label">What's real</span>
        <span>{authentic}</span>
      </div>
      <div className="about__era-row">
        <span className="about__era-label">Sources</span>
        <ul className="about__sources">
          {sources.map((s, i) => (
            <li key={i}>{s}</li>
          ))}
        </ul>
      </div>
    </div>
  );
}

export default function About() {
  return (
    <div className="about">
      <section className="about__section">
        <h3 className="about__h">Credits</h3>
        <p>
          Designed and guided by{" "}
          <Link href="https://diganelin.github.io/">Daniela Ganelin</Link>.
          Code (~13,000 lines) written by{" "}
          <Link href="https://claude.com/claude-code">Claude Code</Link>.
        </p>
        <p className="about__sub">
          Made for high-school students curious about how machines learned to talk.
        </p>
      </section>

      <section className="about__section">
        <h3 className="about__h">Sources, by era</h3>

        <EraSourceBlock
          year="~1960"
          title="Rules for Language"
          authentic="Real ELIZA rules from Weizenbaum (1966); the pattern engine is reimplemented in JavaScript here."
          sources={[
            <>Weizenbaum, J. (1966). "ELIZA — A Computer Program For the Study of Natural Language Communication Between Man And Machine."</>,
            <>Original ELIZA demo: <Link href="https://www.masswerk.at/elizabot/">masswerk.at/elizabot</Link></>,
          ]}
        />

        <EraSourceBlock
          year="~2000"
          title="Machine Learning with Language"
          authentic="Real SMS messages from the UCI corpus. The bag-of-words classifier trains live in your browser."
          sources={[
            <>UCI SMS Spam Collection: <Link href="https://archive.ics.uci.edu/dataset/228/sms+spam+collection">archive.ics.uci.edu/dataset/228</Link></>,
          ]}
        />

        <EraSourceBlock
          year="~2013"
          title="Numbers Can Capture Meaning"
          authentic="Real tweets from the Sentiment140 dataset. Pretrained GloVe word vectors. Sentiment classifier trained live in your browser."
          sources={[
            <>GloVe word vectors (Stanford NLP): <Link href="https://nlp.stanford.edu/projects/glove/">nlp.stanford.edu/projects/glove</Link></>,
            <>Sentiment140 (Go, Bhayani, Huang, Stanford 2009): <Link href="http://help.sentiment140.com/">help.sentiment140.com</Link></>,
          ]}
        />

        <EraSourceBlock
          year="~2018"
          title="Transformers: Generalized Learning"
          authentic="Real text snippets from Wikipedia, Project Gutenberg, and the CPython standard library. Stage 3 generated samples are verbatim from Karpathy's 2015 char-RNN blog post — not generated by this app. GPT-3 training estimates are real published numbers."
          sources={[
            <>Wikipedia (CC BY-SA 4.0): <Link href="https://en.wikipedia.org/">en.wikipedia.org</Link></>,
            <>Project Gutenberg: Hamlet, Huck Finn, Austen, Doyle, Twain, Dickinson (public domain)</>,
            <>Common Crawl sample: <Link href="https://huggingface.co/datasets/agentlans/common-crawl-sample">huggingface.co/datasets/agentlans/common-crawl-sample</Link></>,
            <>GPT-2 (OpenAI 2019): <Link href="https://huggingface.co/openai-community/gpt2">huggingface.co/openai-community/gpt2</Link></>,
            <>Karpathy, A. (2015). "The Unreasonable Effectiveness of Recurrent Neural Networks." <Link href="https://karpathy.github.io/2015/05/21/rnn-effectiveness/">blog post</Link></>,
            <>Brown et al. (2020). "Language Models are Few-Shot Learners." <Link href="https://arxiv.org/abs/2005.14165">arxiv:2005.14165</Link></>,
            <>Patterson et al. (2021). "Carbon Emissions and Large Neural Network Training." <Link href="https://arxiv.org/abs/2104.10350">arxiv:2104.10350</Link></>,
            <>Lambda Labs cost estimate: <Link href="https://lambda.ai/blog/demystifying-gpt-3">lambda.ai/blog/demystifying-gpt-3</Link></>,
            <>Sheng et al. (2019). "The Woman Worked as a Babysitter: On Biases in Language Generation." EMNLP 2019. <Link href="https://arxiv.org/abs/1909.01326">arxiv:1909.01326</Link></>,
            <>Abid, Farooqi, Zou (2021). "Persistent Anti-Muslim Bias in Large Language Models." <Link href="https://arxiv.org/abs/2101.05783">arxiv:2101.05783</Link></>,
            <>Carlini et al. (2021). "Extracting Training Data from Large Language Models." <Link href="https://arxiv.org/abs/2012.07805">arxiv:2012.07805</Link></>,
          ]}
        />

        <EraSourceBlock
          year="~2022"
          title="Training Hard"
          authentic={
            <>
              AI responses are <em>simulated</em> — drafted by a small AI model and hand-edited.
              Tool chips, fake links, the recovery code, and the session URL on the partial-unlock
              path are fabricated. Numeric claims (wages, worker counts, energy use) are grounded
              in the cited sources.
            </>
          }
          sources={[
            <>Perrigo, B. (Jan 2023). "OpenAI Used Kenyan Workers on Less Than $2 Per Hour." <Link href="https://time.com/6247678/openai-chatgpt-kenya-workers/">TIME</Link></>,
            <>Ouyang et al. (2022). "Training language models to follow instructions with human feedback." <Link href="https://arxiv.org/abs/2203.02155">arxiv:2203.02155</Link></>,
            <>Dzieza, J. (June 2023). "AI Is a Lot of Work." <Link href="https://www.theverge.com/features/23764584/ai-artificial-intelligence-data-notation-labor-scale-surge-remotasks-openai-chatbots">The Verge</Link></>,
            <>Patterson et al. (2021). "Carbon Emissions and Large Neural Network Training." <Link href="https://arxiv.org/abs/2104.10350">arxiv:2104.10350</Link></>,
            <>Li et al. (2023). "Making AI Less 'Thirsty': Uncovering and Addressing the Secret Water Footprint of AI Models." <Link href="https://arxiv.org/abs/2304.03271">arxiv:2304.03271</Link></>,
          ]}
        />
      </section>
    </div>
  );
}
