export const ERAS = [
  {
    id: "rules",
    label: "Rules for Language",
    year: "~1960",
    bigIdea: "Hand-craft rules for language.",
    motivation: "Computers were brand new. The only way to make one 'understand' English was to write rules — pattern by pattern, by hand.",
    activity: "Chat with ELIZA, a 1966 therapy bot. Match her rules to her replies, then write your own.",
    newIdea: "Pattern-match keywords and reflect words back. Faked a real-feeling conversation.",
    remainingProblems: "Language is too messy. ELIZA breaks the moment you say something her patterns didn't anticipate.",
  },
  {
    id: "ml",
    label: "Machine Learning with Language",
    year: "~2000",
    bigIdea: "Represent language as numbers, then apply machine learning.",
    motivation: "Spam clogged inboxes. Hand-written rules couldn't keep up. Researchers asked: what if we just count words and let math find the patterns?",
    activity: "Label real SMS messages, train a bag-of-words spam classifier, see where it wins and fails.",
    newIdea: "Count word frequencies in spam vs. legit. The math learns the difference — no rules required.",
    remainingProblems: "The model has no idea what any word means. Synonyms, word order, and context are invisible.",
  },
  {
    id: "embeddings",
    label: "Numbers Can Capture Meaning",
    year: "~2013",
    bigIdea: "Represent each word's meaning as a vector of numbers.",
    motivation: "Around 2013, word2vec and GloVe showed that if you train a model on enough text, words with similar meanings end up close in 'word space.' Meaning itself becomes a coordinate.",
    activity: "Score real tweets, train a sentiment classifier on word vectors, explore meaning in 3D.",
    newIdea: "Words live in a high-dimensional space. King − man + woman ≈ queen. Meaning has math.",
    remainingProblems: "Still no understanding of word order or grammar. 'Dog bites man' looks the same as 'man bites dog.'",
  },
  {
    id: "generative",
    label: "Transformers: Generalized Learning",
    year: "~2018",
    bigIdea: "Train a model to predict the next word on huge text — language and knowledge fall out.",
    motivation: "From 2018 onward, researchers fed transformer models giant text dumps — Wikipedia, books, code, the web — and trained them on one task: predict the next word.",
    activity: "Play the next-word game, watch a model train, then tag what it picked up and what it missed.",
    newIdea: "One task at scale forces the model to learn grammar, biology, history, code — everything text contains.",
    remainingProblems: "Fluent but unreliable. Confidently wrong, biased, sometimes toxic. Needs guardrails.",
  },
  {
    id: "traininghard",
    label: "Training Hard",
    year: "~2022",
    bigIdea: "Supertrain models on real-world performance — human feedback and code execution.",
    motivation: "Pretrained models could write anything, helpful or not. Starting in 2022, labs hired contractors to rate responses, and wired models to code interpreters for verifiable feedback.",
    activity: "Be a contractor rating responses. Be the grader checking code. Try to break the AI's defenses.",
    newIdea: "Use feedback (humans on style, code on correctness) to shape the base model into a helpful assistant.",
    remainingProblems: "Labor cost, compute and water use, and safety gaps where the same training fails on jailbreaks.",
  },
];
