export const ERAS = [
  {
    id: "rules",
    label: "Rules for Language",
    year: "~1966",
    bigIdea: "Hand-craft rules for language.",
    motivation: "Computers were brand new. The only way to make one 'understand' English was to write rules — pattern by pattern, by hand. In 1966 Joseph Weizenbaum wrote ELIZA, a 'therapist' made of about 40 hand-written patterns. It took him by surprise: people poured their hearts out to it, some convinced they were talking to a real person.",
    activity: "Chat with ELIZA yourself. Match her rules to her replies, then write your own.",
    newIdea: "Hand-written rules could drive many language tasks — chatbots like ELIZA, dictionary-based translation, grammar checkers, keyword search.",
    remainingProblems: "Language is too messy. A rule set breaks the moment someone says something the patterns didn't anticipate.",
  },
  {
    id: "ml",
    label: "Machine Learning with Language",
    year: "~2002",
    bigIdea: "Turn language into numbers, then apply machine learning.",
    motivation: "Hand-written rules broke the moment language went off-script. Meanwhile, people's inboxes were drowning in spam. By the early 2000s, researchers tried a different idea for dealing with language: stop writing rules. Just count words and let machine learning find the patterns.",
    activity: "Label real text messages, train a spam classifier, and see where it wins and fails.",
    newIdea: "Once text is numbers, machine learning does the work — no rules required. Good enough for spam filters, document search, and early text classification.",
    remainingProblems: "The computer still doesn't know anything about the meaning of language. It's counting words, not understanding them — synonyms, word order, and context are all invisible.",

  },
  {
    id: "embeddings",
    label: "Numbers Can Capture Meaning",
    year: "~2013",
    bigIdea: "Turn words into numbers that capture meaning.",
    motivation: "Counting words got us spam filters but not meaning. Around 2013, researchers found a way to give every word a list of numbers — and words with similar meanings end up with similar numbers. Machine learning could finally work with meaning, not just word counts.",
    activity: "Place words on a 2D grid by meaning, turn tweets into vectors, and train a sentiment classifier.",
    newIdea: "Represent meaning as numbers. Machine learning can now work with language at a deeper level.",
    remainingProblems: "Still no sense of word order or grammar. \"Dog bites man\" looks the same as \"man bites dog\" — same words, very different stories.",
  },
  {
    id: "generative",
    label: "Generalized Learning with Transformers",
    year: "~2018",
    bigIdea: "Pretrain a Transformer to predict the next word on huge amounts of text.",
    motivation: "Word vectors gave a hint of meaning, but machines still couldn't really work with the structure or deeper meaning of language. From 2018 onward, researchers fed a new kind of specialized neural network — the Transformer — giant piles of text and trained it on one task: predict the next word. Done at massive scale, this one task forces the model to pick up grammar, facts, and common sense all at once. We call this pretraining.",
    activity: "Play the next-word game yourself, watch a model pretrain, then see what it picked up and what it missed.",
    newIdea: "One task at huge scale forces the model to learn the shape of language — grammar, facts, common sense, everything text happens to contain.",
    remainingProblems: "Fluent but unreliable. Confidently wrong, biased, sometimes toxic. It'll say anything that sounds plausible.",
  },
  {
    id: "traininghard",
    label: "Fine-Tuning Transformers",
    year: "~2022",
    bigIdea: "Fine-tune pretrained models with extra training to make them useful.",
    motivation: "A pretrained model will say anything. Starting in 2022, labs added extra training on top — fine-tuning with human feedback, then with automatically-graded code problems — to turn raw predictors into useful assistants.",
    activity: "Rate AI responses as a contractor. Grade code as a program. Try to break a modern AI's defenses.",
    newIdea: "Fine-tuning on top of pretraining shapes the model's behavior — helpful, honest-ish, less toxic. Today's models are powerful enough that this web app's code was written entirely by AI.",
    remainingProblems: "Pretraining, fine-tuning, and using today's language models requires tons of electricity and water — plus low-paid human labor for fine-tuning. Today's powerful models raise alarms about safety and job loss.",
  },
];
